#!/bin/bash

branch_name=$1

# Update master branch
git pull origin "$branch_name"

# Update repository libraries dependencies
cd app/Resources
yarn install

# Compile static assets
gulp build

cd ..
cd ..

# Symfony stuffs

php bin/console doc:dat:drop --force

php bin/console doc:dat:create

php bin/console doc:sc:up --force

php bin/console doc:fix:lo --no-interaction

php bin/console ca:cl --env=prod

php bin/console ca:cl --env=dev
