#!/bin/bash

branch_name=$1

# Update master branch
git pull origin "$branch_name"

# Update repository libraries dependencies
cd app/Resources
yarn install

# Compile static assets
gulp build

cd ..
cd ..

# Symfony stuffs

php bin/console doc:sc:up --force

php bin/consle doc:fix:lo

php bin/console ca:cl --env=prod

php bin/console ca:cl --env=dev
