#!/bin/bash

branch_name=$1

# Update master branch
git pull origin "$branch_name"

# Update repository libraries dependencies
cd app/Resources
yarn install

# Compile static assets
gulp build

cd ..
cd ..

# Tag new release
git checkout -b releasing
git add -f web/css web/img web/js
git commit -m "New release"
git push heroku releasing:master --force

#Back to "$branch_name"
git checkout "$branch_name"

#Delete releasing branch
git branch -D releasing

