#!/bin/bash

branch_name=$1

# Update master branch
git pull origin "$branch_name"

# Update repository libraries dependencies
cd app/Resources
yarn install

# Compile static assets
gulp build

cd ..
cd ..

# Tag new release
git checkout -b releasing
git add -f web/css web/img web/js
git commit -m "New release"
git push heroku releasing:master --force

#Back to "$branch_name"
git checkout "$branch_name"

#Delete releasing branch
git branch -D releasing

#database alignment
mysqldump -uroot -proot nenni > export.sql
mysql -hus-cdbr-iron-east-03.cleardb.net -ub8d5117ca0eb18 -p447d02e5 heroku_a7e469010817ed9 < export.sql
exit

heroku run bash && php bin/console ca:cl --env=prod && exit


