<?php

namespace AppBundle\Repository;

/**
 * BlockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlockRepository extends \Doctrine\ORM\EntityRepository
{
  protected function getBaseQuery()
  {
      return $this->createQueryBuilder('hb')
          ->select('hb')
          ->orderBy('hb.position', 'ASC');
  }

  public function findAllBlocks()
  {
      $qb = $this->getBaseQuery();
      return $qb->getQuery()->getResult();
  }
}
