<?php

namespace AppBundle\Repository;

/**
 * MenuItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuItemRepository extends \Doctrine\ORM\EntityRepository
{
    protected function getBaseQuery()
    {
        return $this->createQueryBuilder('m')
            ->select('m')
            ->orderBy('m.position', 'ASC');
    }

    /**
    * @return array
    */
    public function findMenuItems()
    {
        $qb = $this->getBaseQuery();
        return $qb->getQuery()->getResult();
    }
}
