<?php

namespace AppBundle\Repository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends \Doctrine\ORM\EntityRepository
{
    protected function getBaseQuery($locale)
    {
        return $this->createQueryBuilder('n')
            ->select('n')
            ->join('n.translations', 't')
            ->where('t.locale = :locale')
            ->setParameter('locale', $locale)
            ->addOrderBy('n.date', 'ASC');
    }

  /**
   * @param $locale
   *
   * @param null $limit
   *
   * @return array
   */
    public function findNewsByLocale($locale, $limit = null)
    {
        $qb = $this->getBaseQuery($locale);

        if($limit) {
          $qb->setMaxResults($limit);
        }

        return $qb->getQuery()->getResult();
    }

    /**
     * @param $slug
     *
     * @return array
     */
    public function findSingleNewsBySlug($slug)
    {
        return $this->createQueryBuilder('n')
          ->select('n')
          ->addOrderBy('n.date', 'ASC')
          ->andWhere('n.slug = :slug')
          ->setParameter('slug', $slug)
          ->getQuery()
          ->getOneOrNullResult();
    }
}
