<?php

namespace AppBundle\Repository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends \Doctrine\ORM\EntityRepository
{
    protected function getBaseQuery($locale)
    {
        return $this->createQueryBuilder('n')
            ->select('n')
            ->join('n.translations', 't')
            ->where('t.locale = :locale')
            ->setParameter('locale', $locale)
            ->addOrderBy('n.date', 'ASC');
    }

  /**
   * @param $locale
   *
   * @param null $limit
   *
   * @return array
   */
    public function findNewsByLocale($locale, $limit = null)
    {
        $qb = $this->getBaseQuery($locale);

        if($limit) {
          $qb->setMaxResults($limit);
        }

        return $qb->getQuery()->getResult();
    }

    /**
     * @param $url
     * @param $locale
     *
     * @return array
     */
    public function findSingleNewsByUrlAndLocale($url, $locale)
    {
        $qb = $this->getBaseQuery($locale);
        $qb->andWhere('t.url = :url');
        $qb->setParameter('url', $url);
        return $qb->getQuery()->getOneOrNullResult();
    }
}
