<?php

namespace AppBundle\Repository;

/**
 * SeoBlockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeoBlockRepository extends \Doctrine\ORM\EntityRepository
{
}
