imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: '%default_locale%'

framework:
    #esi: ~
    translator: { fallbacks: ['%default_locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%default_locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        default_locale: '%default_locale%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: "%env(DB_HOST)%"
        port: "%env(DB_PORT)%"
        dbname: "%env(DB_NAME)%"
        user: "%env(DB_USER)%"
        password: "%env(DB_PASSWORD)%"
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

# Sonata
sonata_admin:
    title: Nenni Admin
    title_logo: img/logo.png

sonata_block:
    default_contexts: [cms]
    blocks:
        # enable the SonataAdminBundle block
       sonata.admin.block.admin_list:
           contexts: [admin]

# Vich Uploader
vich_uploader:
    db_driver: orm

    mappings:
        block_image:
            uri_prefix:         /uploads/blocks/images
            upload_destination: '%kernel.root_dir%/../web/uploads/blocks/images'
            namer:              vich_uploader.namer_uniqid

            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true

        block_video:
            uri_prefix:         /uploads/blocks/videos
            upload_destination: '%kernel.root_dir%/../web/uploads/blocks/videos'
            namer:              vich_uploader.namer_uniqid

            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true

# Knp doctrine behaviours
knp_doctrine_behaviors:
    translatable: true

a2lix_translation_form:
    locale_provider: default
    locales: '%active_locales_array%'
    default_locale: '%default_locale%'
    #required_locales: ['%default_locale%']
    templating: "A2lixTranslationFormBundle::default.html.twig"