app:
    resource: '@AppBundle/Controller/SiteController.php'
    type:     annotation
    prefix:   /{_locale}
    options:
        expose: true
    requirements:
        _locale: '%active_locales%'

common:
    resource: '@AppBundle/Controller/CommonController.php'
    type:     annotation
    options:
        expose: true

admin_area:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

fos_js_routing:
    resource: '@FOSJsRoutingBundle/Resources/config/routing/routing.xml'