# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:

    # Managers
    app.blocks_manager:
        class: AppBundle\Manager\BlocksManager
        arguments: ['@doctrine.orm.entity_manager']

    app.news_manager:
        class: AppBundle\Manager\NewsManager
        arguments: ['@doctrine.orm.entity_manager']


    app.common_manager:
        class: AppBundle\Manager\CommonManager
        arguments: ['@doctrine.orm.entity_manager']


    # Subscribers
    app.locale_listener:
        class: AppBundle\EventListener\LocaleListener
        arguments: ['%kernel.default_locale%']
        tags:
            - { name: kernel.event_subscriber }

    app.redirect_listener:
        class: AppBundle\EventListener\RedirectListener
        arguments: ['@router', 'index', '%kernel.default_locale%']
        tags:
            - { name: kernel.event_subscriber }

    # Sonata
    admin.home_blocks:
        class: AppBundle\Admin\HomeBlocksAdmin
        arguments: [~, AppBundle\Entity\Block, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Home, group: "Pagine" }

    admin.la_tenuta_blocks:
        class: AppBundle\Admin\LaTenutaBlocksAdmin
        arguments: [~, AppBundle\Entity\Block, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: La Tenuta, group: "Pagine" }

    admin.vigne_blocks:
        class: AppBundle\Admin\VigneBlocksAdmin
        arguments: [~, AppBundle\Entity\Block, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Le Vigne, group: "Pagine" }

    admin.il_metodo_nenni_blocks:
        class: AppBundle\Admin\IlMetodoNenniBlocksAdmin
        arguments: [~, AppBundle\Entity\Block, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Il Metodo Nenni, group: "Pagine" }

    admin.contatti:
        class: AppBundle\Admin\ContattiBlocksAdmin
        arguments: [~, AppBundle\Entity\Block, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Contatti, group: "Pagine" }

    admin.vini_blocks:
        class: AppBundle\Admin\ViniBlocksAdmin
        arguments: [~, AppBundle\Entity\Block, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Vini, group: "Pagine" }

    # il Team è una sezione di blocchi speciale
    admin.il_team:
        class: AppBundle\Admin\TeamBlocksAdmin
        arguments: [~, AppBundle\Entity\Block, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Le Persone, group: "Il Team" }

    admin.news:
        class: AppBundle\Admin\NewsAdmin
        arguments: [~, AppBundle\Entity\News, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: News, group: "Pagine" }

    admin.menu:
        class: AppBundle\Admin\MenuItemAdmin
        arguments: [~, AppBundle\Entity\MenuItem, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Menu Items, group: "Menu" }
        calls:
            - [ setTemplate, [list, SonataAdminBundle:CRUD:menu_list.html.twig]]

    admin.seo:
        class: AppBundle\Admin\SeoBlocksAdmin
        arguments: [~, AppBundle\Entity\SeoBlock, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Seo, group: "Seo" }