# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:

    # Managers
    app.blocks_manager:
        class: AppBundle\Manager\BlocksManager
        arguments: ['@doctrine.orm.entity_manager']

    app.news_manager:
        class: AppBundle\Manager\NewsManager
        arguments: ['@doctrine.orm.entity_manager']

    # Subscribers
    app.locale_listener:
        class: AppBundle\EventListener\LocaleListener
        arguments: ['%kernel.default_locale%']
        tags:
            - { name: kernel.event_subscriber }

    app.redirect_listener:
        class: AppBundle\EventListener\RedirectListener
        arguments: ['@router', 'index', '%kernel.default_locale%']
        tags:
            - { name: kernel.event_subscriber }

    # Sonata
    admin.home_blocks:
        class: AppBundle\Admin\HomeBlocksAdmin
        arguments: [~, AppBundle\Entity\Block, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Home, group: "Pagine" }

    admin.la_tenuta_blocks:
        class: AppBundle\Admin\LaTenutaBlocksAdmin
        arguments: [~, AppBundle\Entity\Block, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: La Tenuta, group: "Pagine" }

    admin.vigne_blocks:
        class: AppBundle\Admin\VigneBlocksAdmin
        arguments: [~, AppBundle\Entity\Block, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Le Vigne, group: "Pagine" }

    admin.il_metodo_nenni_blocks:
        class: AppBundle\Admin\IlMetodoNenniBlocksAdmin
        arguments: [~, AppBundle\Entity\Block, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Il Metodo Nenni, group: "Pagine" }

    admin.vini_blocks:
        class: AppBundle\Admin\ViniBlocksAdmin
        arguments: [~, AppBundle\Entity\Block, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Vini, group: "Pagine" }

    admin.news:
        class: AppBundle\Admin\NewsAdmin
        arguments: [~, AppBundle\Entity\News, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: News, group: "Pagine" }

    admin.seo:
        class: AppBundle\Admin\SeoBlocksAdmin
        arguments: [~, AppBundle\Entity\SeoBlocksAdmin, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Seo, group: "Seo" }