# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.home_blocks_manager:
        class: AppBundle\Manager\BlocksManager
        arguments: ['@doctrine.orm.entity_manager']

    admin.home_blocks:
        class: AppBundle\Admin\HomeBlocksAdmin
        arguments: [~, AppBundle\Entity\Block, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Home }

    admin.vini_blocks:
        class: AppBundle\Admin\ViniBlocksAdmin
        arguments: [~, AppBundle\Entity\Block, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Vini }

    admin.news:
        class: AppBundle\Admin\NewsAdmin
        arguments: [~, AppBundle\Entity\News, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: News }