# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.home_blocks_manager:
        class: AppBundle\Manager\BlocksManager
        arguments: ['@doctrine.orm.entity_manager']

    admin.home_blocks:
        class: AppBundle\Admin\BlocksAdmin
        arguments: [~, AppBundle\Entity\Block, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Home Block }